### ISSUE TITLE
Release v0.5

### ISSUE THREAD

**Issue by alexiswoo** [contactually/zuora-ruby#56]
Last release available is v0.4 which doesn't handle the REST API.
In the changelog v0.5 is mentioned, but it has not been tagged nor released. Is it possible to release it ?

**Comment by jwg2s** [comment]
@alexiswoo sure - I'll release it right now.

**Comment by jwg2s** [comment]
Done - let me know if you have any issues getting set up, would love to have another set of eyes on this!  We're currently using it in a production environment so it's been pretty well battle-tested at this point.

**Comment by alexiswoo** [comment]
Thanks for your reply ! I will sure keep you up to date if I run into any issue while getting set up. I still can't find the v5.0 release though

**Comment by alexiswoo** [comment]
Thanks! I'll sure keep you up to date if I encounter any issue while getting set up, thanks :)
